title: Visit DC
baseurl: ""
url: ""

theme: minima

plugins:
  - jekyll-relative-links

# Defines the pages to include in the header, and in what order.
# Used by the minima theme.
header_pages:
  - index.md
  - categories.md
  - planner.md

exclude:
  - README.md