title: Visit DC
baseurl: "/visitDC"
url: "https://mreed20.github.io"

theme: minima

plugins:
  - jekyll-relative-links

# Defines the pages to include in the header, and in what order.
# Used by the minima theme.
header_pages:
  - home.md
  - categories.md
  - planner.md

exclude:
  - README.md