title: Visit DC
baseurl: "/visitDC"
url: "https://mreed20.github.io"

# Build settings
theme: minima

# Defines the pages to include in the header, and in what order.
# This is what the Minima theme.
header_pages:
  - index.markdown
  - categories.markdown
  - planner.markdown

exclude:
  - README.md